project:
  type: website

website:
  title: "My Notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://github.com/
      - icon: bi-code-square
        href: https://platform.stratascratch.com/user/mholt
format:
  html:
    theme: cosmo
    css: styles.css



